In [1]:
nums = list(range(1, 26))
# nums = [1,2,3,4,5,6,7,8,9]

In [2]:
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [3]:
len(nums)

25

In [4]:
# !pip install numpy

In [5]:
import numpy as np

In [6]:
mat = np.array(nums).reshape(5,5)

In [7]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
mat[1,3]

np.int64(9)

In [9]:
len(mat)

5

In [10]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
import random

In [12]:
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [13]:
nums1 = nums.copy()
nums2 = nums.copy()

In [14]:
random.shuffle(nums1)
random.shuffle(nums2)


In [15]:
print(nums,nums1,nums2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25] [10, 21, 11, 9, 22, 6, 13, 4, 8, 1, 15, 23, 3, 20, 7, 25, 2, 5, 12, 18, 19, 16, 17, 24, 14] [5, 4, 14, 23, 12, 6, 8, 25, 7, 16, 10, 20, 19, 15, 11, 22, 18, 1, 17, 3, 21, 9, 2, 24, 13]


In [16]:
mat = np.array(nums).reshape(5,5)
mat1 = np.array(nums1).reshape(5,5)
mat2 = np.array(nums2).reshape(5,5)

In [17]:
print(mat,'\n\n')
print(mat1,'\n\n')
print(mat2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 


[[10 21 11  9 22]
 [ 6 13  4  8  1]
 [15 23  3 20  7]
 [25  2  5 12 18]
 [19 16 17 24 14]] 


[[ 5  4 14 23 12]
 [ 6  8 25  7 16]
 [10 20 19 15 11]
 [22 18  1 17  3]
 [21  9  2 24 13]]


In [19]:
nums = list(range(1, 26))

nums1 = nums.copy()
nums2 = nums.copy()

random.shuffle(nums1)
random.shuffle(nums2)

mat1 = np.array(nums1).reshape(5,5)
mat2 = np.array(nums2).reshape(5,5)


i=0

while i < len(nums):
    mynum = int(input("Enter your Numbe  :  "))
    index1 = np.where(mat1 == mynum)
    index2 = np.where(mat2 == mynum)

    mat1[index1] = 0
    mat2[index2] = 0

    # print(mat,'\n\n')
    print(mat1,'\n\n')
    print(mat2)
    print('\n\n\n')


    col_zero_1 = sum(mat1)
    row_zero_1 = sum(np.transpose(mat1))

    col_zero_2 = sum(mat2)
    row_zero_2 = sum(np.transpose(mat2))

    col_index_zero_1 = np.where(col_zero_1 == 0)
    row_index_zero_1 = np.where(row_zero_1 == 0)

    col_index_zero_2 = np.where(col_zero_2 == 0)
    row_index_zero_2 = np.where(row_zero_2 == 0)

    totalzero_1 = len(col_index_zero_1[0]) + len(row_index_zero_1[0])
    totalzero_2 = len(col_index_zero_2[0]) + len(row_index_zero_2[0])

    print('***********************************************')
    print(f'Player 1 cross {totalzero_1} lines.')
    print('\n\n')
    print(f'Player 2 cross {totalzero_2} lines.')
    print('***********************************************')
    print('\n\n\n')

    if totalzero_1 == 5:
        print('Player 1 win')
        break
    elif totalzero_2 == 5:
        print('Player 2 win')
        break
    else:
        i += 1


[[10 21 11  9 22]
 [ 6 13  4  8  0]
 [15 23  3 20  7]
 [25  2  5 12 18]
 [19 16 17 24 14]] 


[[ 5  4 14 23 12]
 [ 6  8 25  7 16]
 [10 20 19 15 11]
 [22 18  0 17  3]
 [21  9  2 24 13]]




***********************************************
Player 1 cross 0 lines.



Player 2 cross 0 lines.
***********************************************




[[10 21 11  9 22]
 [ 6 13  4  8  0]
 [15 23  3 20  7]
 [25  0  5 12 18]
 [19 16 17 24 14]] 


[[ 5  4 14 23 12]
 [ 6  8 25  7 16]
 [10 20 19 15 11]
 [22 18  0 17  3]
 [21  9  0 24 13]]




***********************************************
Player 1 cross 0 lines.



Player 2 cross 0 lines.
***********************************************




[[10 21 11  9 22]
 [ 6 13  4  8  0]
 [15 23  0 20  7]
 [25  0  5 12 18]
 [19 16 17 24 14]] 


[[ 5  4 14 23 12]
 [ 6  8 25  7 16]
 [10 20 19 15 11]
 [22 18  0 17  0]
 [21  9  0 24 13]]




***********************************************
Player 1 cross 0 lines.



Player 2 cross 0 lines.
********************************

In [97]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
col_zero_1 = sum(mat1)
row_zero_1 = sum(np.transpose(mat1))


col_zero_2 = sum(mat2)
row_zero_2 = sum(np.transpose(mat2))

array([55, 60, 65, 70, 75])

In [99]:
row_zero_1 = sum(np.transpose(mat))

array([ 15,  40,  65,  90, 115])

In [100]:
kkk = [1,5,5,7,85,5,54,4,7,5,2,4]

In [102]:
kkk = np.array(kkk)

In [103]:
np.where(kkk == 5)

(array([1, 2, 5, 9]),)

In [115]:
len(np.where(kkk == 5))

1

In [113]:
np.where(kkk == 5)[0]

array([1, 2, 5, 9])

In [114]:
len(np.where(kkk == 5)[0])

4

In [104]:
kkk[np.where(kkk == 5)]

array([5, 5, 5, 5])